import * as Joi from 'joi';

export const configValidationSchema = Joi.object({
  PORT: Joi.number().default(3000),
  NODE_ENV: Joi.string().valid('development', 'production'),
  BACKEND_URL: Joi.string().uri().required(),
  WHATSAPP_CONTACT_NUMBER: Joi.string().required(),
  DATABASE_URL: Joi.string().uri().required(),
  FRONTEND_URL: Joi.string().uri().required(),
  WHATSAPP_META_ACCESS_TOKEN: Joi.string().required(),
  WHATSAPP_META_URL: Joi.string().uri().required(),
  WHATSAPP_WEBHOOK_TOKEN: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_ACCESS_TOKEN_EXPIRES: Joi.string().required(),
  JWT_REFRESH_TOKEN_EXPIRES: Joi.string().required(),
  OTP_LENGTH: Joi.number().required(),
  OTP_VALID_TIME_IN_MINUTES: Joi.number().required(),
  USE_SAME_OTP_FOR_ALL: Joi.boolean().required(),
  OTP_TO_USE: Joi.string().required(),
  THROTTLING_TTL: Joi.number().required(),
  THROTTLING_REQUESTS_LIMIT: Joi.number().required(),
  FILE_LOGGING_ENABLED: Joi.bool().required(),
  DB_LOGGING_ENABLED: Joi.bool().required(),
  CACHING_ENABLED: Joi.bool().required(),
  GOOGLE_MAPS_TOKEN: Joi.string().required(),
  GOOGLE_PLACES_URL: Joi.string().uri().required(),
  AWS_S3_BASE_URL: Joi.string().required(),
  AWS_IAM_ACCESS_KEY_ID: Joi.string().required(),
  AWS_IAM_SECRET_ACCESS_KEY: Joi.string().required(),
  AWS_S3_BUCKET_NAME: Joi.string().required(),
  NI_ACCESS_TOKEN_URL: Joi.string().required(),
  NI_CREATE_PAYMENT_URL: Joi.string().required(),
  TWILIO_ACCOUNT_SID: Joi.string().required(),
  TWILIO_AUTH_TOKEN: Joi.string().required(),
  TWILIO_SMS_SEND_URL: Joi.string().required(),
  TWILIO_FROM_PHONE: Joi.string().required(),
  TWILIO_TEST_NUMBERS: Joi.string().required(),
  AWS_REGION: Joi.string().required(),
  SMS_SERVICE_ENABLED: Joi.boolean().required(),
  WHATSAPP_SERVICE_ENABLED: Joi.boolean().required(),
  SAMPLE_WHATSAPP_PHONE_NUMBER: Joi.string().required(),
});
